
/* Generated by Interface Builder */

#import <SynthesisCore/SIMCell.h>
#import <SynthesisCore/SIMType.h>
#import <SynthesisCore/SIMInputChannel.h>
#import <SynthesisCore/Simulator.h>

#define INTANDFIRE_RestingPotential		@"RestingPotential"
#define INTANDFIRE_VoltageTimeConstant		@"VoltageTimeConstant"
#define INTANDFIRE_RestingThreshold		@"RestingThreshold"
#define INTANDFIRE_PotassiumReversalPotential	@"PotassiumReversalPotential"
#define INTANDFIRE_SodiumReversalPotential	@"SodiumReversalPotential"
#define INTANDFIRE_SpikeActivation		@"SpikeActivation"
#define INTANDFIRE_ThresholdTimeConstant	@"ThresholdTimeConstant"
#define INTANDFIRE_ThresholdVoltageCoefficient	@"ThresholdVoltageCoefficient"

#define THRESHOLD @"Threshold"
#define LASTSPIKE @"LastSpikeTime"

@interface IntAndFire:SIMCell
{
    float E0;		/* resting potential */
    float tcV;		/* voltage time constant */
    float Th0;		/* resting threshold */
    float EK;		/* potassium reversal */
    float ENa;		/* sodium reversal */
    float c;		/* voltage coefficient in Th diff eq. */
    float d;		/* spike activation of threshold */
    float tcTh;		/* threshold time constant */

    unsigned int	state,V,Th,lastSpike;
}

@end
