
/* Generated by Interface Builder */

#import <SynthesisCore/SIMCell.h>
#import <SynthesisCore/SIMType.h>
#import <SynthesisCore/SIMInputChannel.h>
#import <SynthesisCore/SIMPatternGenerator.h>
#import <SynthesisCore/Simulator.h>

#define	SIMRefractoryPeriodKey	@"RefractoryPeriod"
#define	SIMPatternGeneratorKey	@"PatternGenerator"

#define	Refractory		@"Refractory"
#define GeneratorSeed		@"GeneratorSeed"
#define DEFAULT_SEED		1000


@interface PatternBasedNeuron:SIMCell
{
    id patternGenerator;
    id generator;
    float refractoryPeriod;
    unsigned int refractory;
}

- (Class)_patternGeneratorClassForValue:(NSString *)value;

@end
